In [1]:
import numpy as np
import pandas as pd

community_event = pd.read_csv('community_evolution_matrix.csv')

In [2]:
# time1 time2
# xxxtime1
# Read data../visualization/assets/data/xxx/handle/rankxxx.csv
# time1communityfieldid.time2commmunityid
# time1idtime2id, , # : t1_idt2_id/t1_id

def find_most_similar_community(time1, community_number, time2):
 """
 time2time1communitycommunity

 :
 time1: , time ( "2015")
 community_number: , time1community
 time2: , time ( "2016")

 :
 most_similar_comm: time2community
 max_similarity: ()
 """
 # readtime1data
 t1_data = pd.read_csv(f'../visualization/assets/data/{time1}/handle/rank{time1}.csv')

 # readtime2data
 t2_data = pd.read_csv(f'../visualization/assets/data/{time2}/handle/rank{time2}.csv')

 # time1communitynodeID
 t1_community_ids = set(t1_data[t1_data['community'] == community_number]['id'])

 # time1community, None
 if len(t1_community_ids) == 0:
 return None, 0

 # time2community
 t2_communities = t2_data['community'].unique()

 max_similarity = 0
 most_similar_comm = None

 # time2communitytime1community
 for comm in t2_communities:
 t2_community_ids = set(t2_data[t2_data['community'] == comm]['id'])
 intersection = t1_community_ids.intersection(t2_community_ids)

 # : time1community
 similarity = len(intersection) / len(t1_community_ids)

 #  if similarity > max_similarity:
 max_similarity = similarity
 most_similar_comm = comm

 return most_similar_comm, max_similarity

In [38]:
community_event

,202401,202402,202403,202404,202405,202406,202407,202408,202409,202410
0,2,31,6,7,13.0,0.0,14.0,13.0,2,13
1,1,10,0,4,2.0,14.0,3.0,2.0,4,8
2,3,"[8, 35]","[2, 12]","[1, 2]",7.0,7.0,0.0,0.0,6,"[2, 32]"
3,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,9,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0,2,4,0,8.0,6.0,4.0,15.0,0,11
7,10,9,3,3,4.0,3.0,8.0,21.0,"[1, 7]",5
8,5,0,1,8,9.0,11.0,6.0,3.0,8,17
9,13,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,14,44,20,14,22.0,28.0,17.0,20.0,20,NaN
11,16,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,18,53,17,16,19.0,24.0,20.0,24.0,16,NaN
13,19,54,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,20,55,19,18,21.0,26.0,22.0,26.0,17,NaN

In [ ]:
# community_event, 2NaN, Nan, , NaN(); , , visualization/assets/data/events/community_events.csv

In [ ]:
# readeventtypedata
events_data = pd.read_csv('../visualization/assets/data/events/community_events.csv')

# processcommunity_event
filled_community_event = community_event.copy()

# for idx, row in filled_community_event.iterrows():
 # NaN
 nan_indices = row.index[row.isna()].tolist()
 nan_count = len(nan_indices)

 if nan_count >= 2:
 all_cols = filled_community_event.columns.tolist()

 # NaNNaN
 for i in range(1, nan_count):
 current_nan_col = nan_indices[i]

 # NaNcolumn()
 valid_cols = [col for col in all_cols if col not in nan_indices[:i + 1] and pd.notna(row[col])]

 # column
 prev_cols = [col for col in valid_cols if all_cols.index(col) < all_cols.index(current_nan_col)]

 if prev_cols:
 prev_col = prev_cols[-1] # column
 prev_value = row[prev_col]

 # time
 time1 = prev_col
 time2 = current_nan_col

 # events_data
 match_found = False
 if not events_data.empty:
 matches = events_data[(events_data['source_date'] == int(time1)) &
 (events_data['source_community'] == str(prev_value)) &
 (events_data['target_date'] == int(time2))]

 if not matches.empty:
 match_found = True
 target_community = matches.iloc[0]['target_community']
 # NaN, event
 filled_community_event.at[idx, current_nan_col] = target_community

 # eventtype()
 if 'event' in filled_community_event.columns and 'event_type' in matches.columns:
 filled_community_event.at[idx, 'event'] = matches.iloc[0]['event_type']

 # event, similarity
 if not match_found:
 most_similar, similarity = find_most_similar_community(str(time1), int(prev_value), str(time2))

 if most_similar is not None:
 filled_community_event.at[idx, current_nan_col] = int(most_similar)

# data
filled_community_event
# savedata
filled_community_event.to_csv('filled_community_evolution_matrix.csv', index=False)

In [ ]:
most_similar, A = find_most_similar_community("202407", 26, "202408")
int(most_similar),A

In [ ]:
print(events_data[(events_data['source_date'] == 202404) &
 (events_data['source_community'] == "0") &
 (events_data['target_date'] == 202405)])

In [50]:
# # communitymatrix(timecommunity)
filled_community_event = pd.read_csv('filled_community.csv')

# column(exists'event'column)
time_columns = [col for col in filled_community_event.columns if col != 'event']
first_time_col = time_columns[0]

# timedata
try:
 first_time_data = pd.read_csv(f'../visualization/assets/data/{first_time_col}/handle/rank{first_time_col}.csv')

 # createcommunity
 community_sizes = {}

 # community(node)
 for comm in first_time_data['community'].unique():
 community_sizes[comm] = len(first_time_data[first_time_data['community'] == comm])

 # createcolumncommunity,  filled_community_event['community_size'] = filled_community_event[first_time_col].map(
 lambda x: community_sizes.get(int(x), 0) if pd.notna(x) and not isinstance(x, str) else 0
 )

 # community
 sorted_community_event = filled_community_event.sort_values(by='community_size', ascending=False)

 # deletecolumn
 sorted_community_event = sorted_community_event.drop(columns=['community_size'])

 # save
 sorted_community_event.to_csv('sorted_community_evolution.csv', index=False)

 print(f"time({first_time_col})communitysavesorted_community_evolution.csv")

except FileNotFoundError:
 print(f"time{first_time_col}datafile")

time(202401)communitysavesorted_community_evolution.csv

In [3]:
# create1community_eventdf1, communitysize
# readfilled_community_evolution_matrix.csv, community, communitytimenode, df1
# communitynoderead../visualization/assets/data/xxx/handle/rankxxx.csv
# xxtime, filled_community_evolution_matrix.csvcolumn name
# communityfilled_community_evolution_matrix.csv

# readcommunitymatrix
filled_community_matrix = pd.read_csv('../visualization/assets/data/matrix/new_community_evolution.csv')

# createDataFramecommunity
community_sizes = filled_community_matrix.copy()

# timecolumn(���'event'column)
time_columns = [col for col in filled_community_matrix.columns if col != 'event']

# createdatareadfile
rank_data_cache = {}

# timedata
for time_col in time_columns:
 try:
 rank_data_cache[time_col] = pd.read_csv(f'../visualization/assets/data/{time_col}/handle/rank{time_col}.csv')
 print(f"Loaded data for time {time_col}")
 except FileNotFoundError:
 print(f"Warning: File for time {time_col} not found.")
 rank_data_cache[time_col] = None

# timecolumn
for idx, row in filled_community_matrix.iterrows():
 for time_col in time_columns:
 community_number = row[time_col]

 # communityNaN
 if pd.notna(community_number):
 # 1: 0, -1
 if community_number is None:
 community_sizes.at[idx, time_col] = -1
 # 2: column, process
 elif isinstance(community_number, str) and community_number.startswith('[') and community_number.endswith(
 ']'):
 try:
 # column
 community_list = eval(community_number)
 if isinstance(community_list, list):
 size_list = []
 for comm in community_list:
 if rank_data_cache[time_col] is not None:
 comm_size = len(
 rank_data_cache[time_col][rank_data_cache[time_col]['community'] == int(comm)])
 size_list.append(comm_size)
 else:
 size_list.append(float('nan'))
 community_sizes.at[idx, time_col] = str(size_list)
 except:
 community_sizes.at[idx, time_col] = float('nan')
 # : community
 elif rank_data_cache[time_col] is not None:
 # community
 community_int = int(community_number)

 # communitynode
 community_size = len(rank_data_cache[time_col][rank_data_cache[time_col]['community'] == community_int])

 # community
 community_sizes.at[idx, time_col] = community_size
 else:
 community_sizes.at[idx, time_col] = float('nan')
 else:
 # communityNaN, NaN
 community_sizes.at[idx, time_col] = float('nan')

# savecommunitymatrix
community_sizes.to_csv('new_community_sizes_matrix.csv', index=False)
print("Community sizes matrix saved to community_sizes_matrix.csv")

# community_sizes.head()

Loaded data for time 202401
Loaded data for time 202402
Loaded data for time 202403
Loaded data for time 202404
Loaded data for time 202405
Loaded data for time 202406
Loaded data for time 202407
Loaded data for time 202408
Loaded data for time 202409
Loaded data for time 202410
Community sizes matrix saved to community_sizes_matrix.csv

,202401,202402,202403,202404,202405,202406,202407,202408,202409,202410
0,13085,22516,16262,17090,12912,13904,11902,14731,14153,19575
1,7478,0,16262,17090,12912,13904,11902,14731,14153,19575
2,12732,11773,15678,11505,14105,14384,14684,12904,16440,20360
3,12256,10892,10952,12373,13115,11502,12743,12112,10503,16936
4,42,10,0,12775,11925,0,0,0,0,0

In [1]:
# createcommunitymatrix
import pandas as pd
import numpy as np

# readcommunitymatrix
filled_community_matrix = pd.read_csv('../visualization/assets/data/matrix/new_community_evolution.csv')

# createDataFramecommunity
community_influence = filled_community_matrix.copy()

# timecolumn(exists'event'column)
time_columns = [col for col in filled_community_matrix.columns if col != 'event']

# createdatareadfile
super_node_cache = {}

# timedata
for time_col in time_columns:
 try:
 super_node_cache[time_col] = pd.read_csv(f'../visualization/assets/data/{time_col}/handle/superNode.csv')
 print(f"Loaded superNode data for time {time_col}")
 except FileNotFoundError:
 print(f"Warning: superNode file for time {time_col} not found.")
 super_node_cache[time_col] = None

# timecolumn
for idx, row in filled_community_matrix.iterrows():
 for time_col in time_columns:
 community_number = row[time_col]

 # communityNaN
 if pd.notna(community_number) and community_number != -1:
 # : column, process
 if isinstance(community_number, str) and community_number.startswith('[') and community_number.endswith(']'):
 try:
 # column
 community_list = eval(community_number)
 if isinstance(community_list, list):
 influence_list = []
 for comm in community_list:
 if super_node_cache[time_col] is not None:
 # communityinfluence
 comm_data = super_node_cache[time_col][super_node_cache[time_col]['community'] == int(comm)]
 if not comm_data.empty:
 influence = round(float(comm_data.iloc[0]['influence']), 2)
 influence_list.append(influence)
 else:
 influence_list.append(float('nan'))
 else:
 influence_list.append(float('nan'))
 community_influence.at[idx, time_col] = str(influence_list)
 except:
 community_influence.at[idx, time_col] = float('nan')
 # : influence
 elif super_node_cache[time_col] is not None:
 # community
 community_int = int(community_number)

 # communityinfluence
 comm_data = super_node_cache[time_col][super_node_cache[time_col]['community'] == community_int]
 if not comm_data.empty:
 influence = round(float(comm_data.iloc[0]['influence']), 2)
 community_influence.at[idx, time_col] = influence
 else:
 community_influence.at[idx, time_col] = float('nan')
 else:
 community_influence.at[idx, time_col] = float('nan')
 else:
 # communityNaN-1, influenceNaN
 community_influence.at[idx, time_col] = float('nan')

# savecommunitymatrix
community_influence.to_csv('../visualization/assets/data/matrix/new_community_influence_matrix.csv', index=False)
print("Community influence matrix saved to new_community_influence_matrix.csv")

Loaded superNode data for time 202401
Loaded superNode data for time 202402
Loaded superNode data for time 202403
Loaded superNode data for time 202404
Loaded superNode data for time 202405
Loaded superNode data for time 202406
Loaded superNode data for time 202407
Loaded superNode data for time 202408
Loaded superNode data for time 202409
Loaded superNode data for time 202410
Community influence matrix saved to new_community_influence_matrix.csv

/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '227.43' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence
/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '403.44' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence
/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '287.95' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence
/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '297.25' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence
/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '220.07' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence
/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '251.35' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence
/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '216.12' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence
/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '262.53' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence
/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '261.74' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence
/tmp/ipykernel_326628/3676878976.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '305.87' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
 community_influence.at[idx, time_col] = influence